
redis: &redis
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *redis
  channel_prefix: game_scalaxy_development

test:
  <<: *redis
  channel_prefix: game_scalaxy_test

production:
  <<: *redis
  channel_prefix: game_scalaxy_production

